### ISSUE TITLE
Topper API support

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/api-telos-net#92]
**Description**
Add endpoint to generate bootstrap token used for Topper Pay widget link forwarding

**Tasks**
- [x] add widget pk as AWS secret
- [x] add lib to generate token
- [x] add route that accepts address as optional query param
- [x] add optional sandbox flag for testing
- [x] exclude route from swagger

**Comment by pmjanus** [comment]
Blocks wallet topper integration.
